name: tt_5
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  path: ^1.8.3
  intl: ^0.19.0
  uuid: ^4.3.3
  in_app_review: ^2.0.9
  flutter_app_info: ^1.1.2
  flutter_markdown: ^0.7.2
  dropdown_button2: ^2.3.9
  equatable: ^2.0.5
  hive: ^2.2.3
  fl_chart: ^0.65.0
  camera: ^0.10.5+9
  flutter_staggered_grid_view: ^0.7.0
  hive_flutter: ^1.1.0
  pull_down_button: ^0.9.4
  firebase_core: ^3.0.0
  firebase_crashlytics: ^4.0.1
  firebase_remote_config: ^5.0.1
  get_it: ^7.7.0
  connectivity_plus: ^5.0.2
  webview_flutter: ^4.8.0
  webview_flutter_android: ^3.16.4
  webview_flutter_wkwebview: ^3.13.1
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.14.1
  dots_indicator: ^3.0.0
  table_calendar: ^3.0.9
  collection: ^1.18.0
  easy_date_timeline: ^1.1.3
  flagsmith: ^6.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

  flutter_lints: ^3.0.0

flutter_native_splash:
  image: "assets/icon.png"
  color: '#9AB16A'

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/

  fonts:
    - family: Amiko
      fonts:
        - asset: assets/fonts/Amiko-Bold.ttf
          weight: 700
        - asset: assets/fonts/Amiko-SemiBold.ttf
          weight: 600
    - family: Amiko
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600

